### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by tom-doerr** [tremorlabs/tremor-npm#74]
When I add
```
 <ProgressBar percentageValue={ 32 } marginTop="mt-2" />
```
it correctly displays the progressbar when automatically reloading the site, but throws the error `TypeError: Cannot read properties of null (reading 'useState')` when I manually load the site.
Full error message:
```
cont_2-frontend-1  | Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
cont_2-frontend-1  | 1. You might have mismatching versions of React and the renderer (such as React DOM)
cont_2-frontend-1  | 2. You might be breaking the Rules of Hooks
cont_2-frontend-1  | 3. You might have more than one copy of React in the same app
cont_2-frontend-1  | See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
cont_2-frontend-1  | TypeError: Cannot read properties of null (reading 'useState')
cont_2-frontend-1  |     at Object.useState (/node_modules/react/cjs/react.development.js:1622:21)
cont_2-frontend-1  |     at /node_modules/@tremor/react/dist/cjs/index.js:249:382363
cont_2-frontend-1  |     at renderWithHooks (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
cont_2-frontend-1  |     at renderIndeterminateComponent (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
cont_2-frontend-1  |     at renderElement (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
cont_2-frontend-1  |     at renderNodeDestructiveImpl (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
cont_2-frontend-1  |     at renderNodeDestructive (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
cont_2-frontend-1  |     at renderForwardRef (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
cont_2-frontend-1  |     at renderElement (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
cont_2-frontend-1  |     at renderNodeDestructiveImpl (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
cont_2-frontend-1  | error - TypeError: Cannot read properties of null (reading 'useState')
cont_2-frontend-1  |     at Object.useState (/node_modules/react/cjs/react.development.js:1622:21)
cont_2-frontend-1  |     at /node_modules/@tremor/react/dist/cjs/index.js:249:382363
cont_2-frontend-1  |     at renderWithHooks (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
cont_2-frontend-1  |     at renderIndeterminateComponent (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
cont_2-frontend-1  |     at renderElement (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
cont_2-frontend-1  |     at renderNodeDestructiveImpl (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
cont_2-frontend-1  |     at renderNodeDestructive (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
cont_2-frontend-1  |     at renderForwardRef (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
cont_2-frontend-1  |     at renderElement (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
cont_2-frontend-1  |     at renderNodeDestructiveImpl (/frontend/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11) {
cont_2-frontend-1  |   page: '/'
cont_2-frontend-1  | }
```

Am I doing something wrong or is this an issue with tremor?

**Comment by tom-doerr** [comment]
Solved it. The solution might have been to install the packages with npm instead of yarn.
